<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>my_env_mujoco</name>
  <version>1.0.0</version>
  <description>This package contains a mujoco environment for dual UR robots.</description>
  <maintainer email="user@email.com">Your Name</maintainer>
  <license>Apache License 2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>rclcpp_action</depend>
  <depend>std_msgs</depend>
  <depend>control_msgs</depend>
  <depend>joint_trajectory_controller</depend>
  <depend>velocity_controllers</depend>
  <depend>force_torque_sensor_broadcaster</depend>
  <exec_depend>rviz2</exec_depend>
  <exec_depend>xacro</exec_depend>
  <exec_depend>controller_manager</exec_depend>
  <!-- OCS2 仿真版 launch（start_my_env_mujoco_ocs2.launch.py）运行依赖 -->
  <exec_depend>my_env_control</exec_depend>
  <exec_depend>my_env_description</exec_depend>
  <exec_depend>mujoco_ros2_control</exec_depend>
  <exec_depend>mujoco_ros2_control_plugins</exec_depend>


  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>